version: '3'

services:
    backend:
        build:
            context: ./Backend
            dockerfile: ./Dockerfile
        image: "react-frontend-nginx"
        ports:
            - "8000:8000"
    frontend:
        build:
            context: ./FrontEnd
            dockerfile: ./Dockerfile
        image: "node-backend-express"
        ports:
            - "3000:80"